/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 18 03:03:27 GMT 2017
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.InputMismatchException;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class JavaCalc_ESTest extends JavaCalc_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SystemInUtil.addInputLine("71");
      SystemInUtil.addInputLine("1");
      SystemInUtil.addInputLine("1");
      JavaCalc.main((String[]) null);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        JavaCalc.main((String[]) null);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String[] stringArray0 = new String[9];
      SystemInUtil.addInputLine("9Eaw!RX(cS*bPR$?U");
      // Undeclared exception!
      try { 
        JavaCalc.main(stringArray0);
        fail("Expecting exception: InputMismatchException");
      
      } catch(InputMismatchException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SystemInUtil.addInputLine("33");
      SystemInUtil.addInputLine("33");
      SystemInUtil.addInputLine("33");
      JavaCalc.main((String[]) null);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SystemInUtil.addInputLine("4");
      SystemInUtil.addInputLine("4");
      SystemInUtil.addInputLine("4");
      JavaCalc.main((String[]) null);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      SystemInUtil.addInputLine("2");
      SystemInUtil.addInputLine("2");
      SystemInUtil.addInputLine("2");
      JavaCalc.main((String[]) null);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      SystemInUtil.addInputLine("3");
      SystemInUtil.addInputLine("2");
      SystemInUtil.addInputLine("3");
      JavaCalc.main((String[]) null);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      SystemInUtil.addInputLine("71");
      SystemInUtil.addInputLine("71");
      SystemInUtil.addInputLine("1");
      String[] stringArray0 = new String[1];
      JavaCalc.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      JavaCalc javaCalc0 = new JavaCalc();
  }
}
